# Use root/example as user/password credentials
version: '3.3'

services:
    mongodb:
        image: mongo:latest
        restart: always
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - "27017:27017"
        environment:
            - MONGODB_ROOT_PASSWORD=pass
        networks:
            - video_recoreder_network
     
    app: # The namme of the servide
        container_name: video_recorder_front # Name of container
        build: ./video-recorder-app # Location of our Dockerfile
        volumes: # Volume binding
            - './video-recorder-app:/usr/src/app' # load local directory inside of container
        ports: 
            - '4200:4200' # Port mapping
        command: > # to do -- check if work corctly with websoket 
            bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"


    api:
        container_name: video_recorder_server
        build: ./video-recorder-api # Location of our Dockerfile
        volumes: # Volume binding
            - './video-recorder-api:/usr/src/api' # load local directory inside of container
        ports:
            - '3000:3000'
        depends_on:
            - mongodb
        networks:
            - video_recoreder_network
        links:
            - mongodb
        environment:
            WAIT_HOSTS: mongodb
        command: > # to do -- check if work corctly with websoket 
            bash -c "npm install && npm run start:dev --host 0.0.0.0 --port 3000"


    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - 'ME_CONFIG_OPTIONS_EDITORTHEME=ambiance'
            - 'ME_CONFIG_BASICAUTH_USERNAME=user'
            - 'ME_CONFIG_BASICAUTH_PASSWORD=pass'
            - 'ME_CONFIG_MONGODB_SERVER=mongodb'
        links:
            - mongodb
        networks:
            - video_recoreder_network

volumes:
    mongodb:
    mongodb_config:

networks:
    video_recoreder_network:
        driver: bridge


  
